### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by hset911** [watsonyanghx/CNN_LSTM_CTC_Tensorflow#6]
use 60*180size to train ,num_classes = 12 then i got it

loading train data, please wait---------------------
('get image: ', 15000)
loading validation data, please wait---------------------
('get image: ', 4999)
2017-11-06 13:16:08.547013: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-06 13:16:08.641450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-06 13:16:08.641675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.86
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.29GiB
2017-11-06 13:16:08.641691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
=============================begin training=============================
No handlers could be found for logger "Traing for OCR using CNN+LSTM+CTC"
('batch', 99, ': time', 0.1522228717803955)
('batch', 199, ': time', 0.1701350212097168)
('batch', 299, ': time', 0.14639997482299805)
('batch', 99, ': time', 0.1512739658355713)
Traceback (most recent call last):
  File "main.py", line 215, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 207, in main
    
  File "main.py", line 111, in train
    
ValueError: need more than 2 values to unpack

**Comment by QiangXie** [comment]
I have met the similar problem, I think this problem is caused by the mismatch between the number of ops and the number of  return values,。 Obviously，lastbatch_err don't have corresponding op.

**Comment by 980044579** [comment]
```python
                            dense_decoded,lastbatch_err , lr = \
                                sess.run([model.dense_decoded, model.lrn_rate],
                                         val_feed)
```
sees.run() only return two values,you just need to remove "lastbatch_err ",good luck

**Comment by hset911** [comment]
@QiangXie @980044579 thanks，I have solve it by your solutions.
